### ISSUE TITLE
"The evaluation has already been requested" in case of no student to be synced.

### ISSUE THREAD

**Issue by tobiasreischmann** [learnweb/moodle-block_evasys_sync#21]
A evaluation coordinator contacted me that there was an error with the evaluation request. Although there were students in the course, there were no students in evasys. However, the teacher still received the "The evaluation has already been requested" pop-up and no students were synced. The evasys course id was correct and no evaluation did exist.
We should recheck the if conditions, for which "The evaluation has already been requested" is returned.

**Comment by tobiasreischmann** [comment]
The bug was, that the course did only contain user in the role of a tutor rather than a student. We should adapt the responses of the system and a response: "There was no student to be synched" or something like that.

**Comment by Dagefoerde** [comment]
You can sync as often as you want to, each time incrementally adding new participants to the list.
If this problem occurs, check whether the expected participants have the `mayevaluate` capability.

**Comment by rtschu** [comment]
Tobias: Please merge on master and the current development state

**Comment by Dagefoerde** [comment]
Closed via #34
