### ISSUE TITLE
Change descriptions of / near the synchronisation button

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_evasys_sync#4]
It is not made clear to teachers what exactly will happen when the sync button is pressed. Some assume that all students will immediately get email invitations – they won't. Some do not realise that an email to the person responsible for evaluations will be sent, thus implying a call to action.

This needs more explanations, a clearer description, or both.

**Comment by tobiasreischmann** [comment]
We should alter the button text or add an additional description on top.
Also, a message should pop up after the button has pressed, which tells the teacher, what just happened and what next steps might be done by the person responsible for evaluations.

**Comment by Dagefoerde** [comment]
Closed via #13
