### ISSUE TITLE
Let teachers define when the evaluation period starts and ends

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_evasys_sync#6]
EvaSys allows users to define start and end dates for individual course evaluations. Let teachers define this evaluation period on their own.

This implies that teachers can control the point in time at which students are invited to participate. Maybe include a "now" option for start date...

These settings could be located close to the synchronisation; e.g., as part of the same process.

**Comment by tobiasreischmann** [comment]
The results of this setting should be in a first version:
- These dates are added as additional information to the mail for the person responsible for the evaluation.
In a second version:
- These dates are used for automatically starting and ending the rating period
