### ISSUE TITLE
Support synchronisation of participants for multiple (LSF) courses at once.

### ISSUE THREAD

**Issue by Dagefoerde** [learnweb/moodle-block_evasys_sync#7]
At the university there are several "combined modules", such as modules consisting of a lecture and an exercise. There modules are treated separately in campus management (LSF), and are also managed separately in EvaSys. However, many of these combined modules share an integrated Moodle course.

Right now, this plugin assumes that there is a 1:1 relation between a Moodle course and an LSF course (and, therefore, Moodle course -- EvaSys course). This does not suit the reality. It needs to be extended towards an 1:n relation, so that a Moodle course can push participants to more than one EvaSys course.

On synchronisation, we can prompt the teacher whether participants should be pushed to additional courses. We need to take care that teachers only synchronise with courses that they are actually teaching, i.e. we require a mechanism similar to that of our autonomous course requests (cf. https://github.com/learnweb/his_unification).

**Comment by rtschu** [comment]
I think #17 closed this, right?
